name: Build and push docker image

on:
  push:

jobs:
  build_and_push1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: docker build
        run: docker build -t EMELEN_BACKEND:LATEST .