name: Build and push docker image

on:
  push:

jobs:
  build_and_push1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Docker build
        run: |
          echo "MONGO_USER=chukwuemelieoguejiofor_db_user" >> .env
          echo "MONGO_PASSWORD=68XZ2P2RRCCNxTR4" >> .env
          echo "MONGO_CLUSTER=cluster0.hqahfia.mongodb.net/" >> .env
          cat env.example
         # ls -la
         # docker build -t emelen_backend:latest .